AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
# Description: >
#   Unpack Bulk Request

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
Resources:
  UnpackBulkReqFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: unpackBulkRequest-test-ds
      Role: arn:aws:iam::544116674215:role/matchingEngineIamLambdaExecutionRole
      CodeUri: ./unpack_req
      Handler: unpackBulkReq.execute
      Runtime: python3.8
      Events:
        PMatch:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /itemMatch
            Method: post
            Auth:
              Authorizer: null

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  UnpackBulkReqApi:
    Description: "API Gateway endpoint URL for Prod stage for unpackBulkRequest function"
    Value: "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Test/itemMatch/"
