AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  unpack

  Sample SAM Template for unpack

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  UnpackThreadFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: unpackBulkThread-test
      Description: SAM unpackBulk
      Role: arn:aws:iam::544116674215:role/matchingEngineIamLambdaExecutionRole
      CodeUri: unpack_thread/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Events:
        UnpackThreadAPI:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /itemMatch
            Method: post
            Auth:
              Authorizer: null

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  UnpackThreadAPI:
    Description: "API Gateway endpoint URL for UnpackBulk"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/itemMatch"
  UnpackThreadFunction:
    Description: "Unpack thread function ARN"
    Value: !GetAtt UnpackThreadFunction.Arn
