AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  programme_match_req

  Sample SAM Template for programme_match_req

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
Resources:
  
  PrMatchFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName : programmeMatchFunction
      Role: arn:aws:iam::544116674215:role/matchingEngineIamLambdaExecutionRole
      CodeUri: ./programme_match_req
      Handler: programme_match_req.p_match_req
      Runtime: python3.8
      Layers:
        - arn:aws:lambda:eu-west-1:544116674215:layer:query_management:4
        - arn:aws:lambda:eu-west-1:544116674215:layer:elasticsearch_metadata:3
      Events:
        PMatch:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /pmatch
            Method: get
      Policies:
      - Statement:
        - Effect: "Allow" 
          Action: 
            - 'lambda:GetLayerVersion' 
          Resource: 
            - 'arn:aws:lambda:*:503986983991:layer:*:*'    
        
  CreateUpdateFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName : createUpdateFunction
      Role: arn:aws:iam::544116674215:role/matchingEngineIamLambdaExecutionRole
      CodeUri: ./create_update_item
      Handler: create_update.create_update_item
      Runtime: python3.8
      Layers:
        - arn:aws:lambda:eu-west-1:544116674215:layer:elasticsearch_metadata:3
      
      Policies:
      - Statement:
        - Effect: "Allow" 
          Action: 
            - 'lambda:GetLayerVersion' 
          Resource: 
            - 'arn:aws:lambda:*:544116674215:layer:*:*'

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  PMatchApi:
    Description: "API Gateway endpoint URL for Prod stage for Match function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/pmatch/"